# Deploying {{projectName}}
#
# First, install Docker. Then create the project data folder:
# $ mkdir /path/to/project-data
# $ cd /path/to/project-data
# $ wget https://github.com/namlook/docker-virtuoso/raw/master/virtuoso.ini
# ... edit config
#
# start virtuoso:
# $ docker run -d --name virtuoso -v /path/to/project-data:/home/virtuoso/virtuoso/var/lib/virtuoso/db virtuoso:7.1.0
#
# change dba password:
# $ isql -H <virtuoso-container-id> exec='set password dba abetterpassword;'
#
# enable SPARQL UPDATE (you must have an isql client: apt-get install virtuoso-opensource):
# $ isql -P abetterpassword -H <virtuoso-container-id> exec='grant SPARQL_UPDATE to "SPARQL";'
#
# start {{projectName}}:
# docker run -d -p <host-port>:{{port}} --link virtuoso:db --name {{dasherizedProjectName}} {{organisation}}/{{dasherizedProjectName}}:{{version}}

FROM dockerfile/nodejs
MAINTAINER {{{author}}}
RUN adduser --disabled-password --home=/home/{{dasherizedProjectName}} --gecos "" {{dasherizedProjectName}}
ADD . /home/{{dasherizedProjectName}}/app
RUN chown -R {{dasherizedProjectName}}:{{dasherizedProjectName}} /home/{{dasherizedProjectName}}
WORKDIR /home/{{dasherizedProjectName}}/app
EXPOSE {{port}}
USER {{dasherizedProjectName}}
CMD npm start